### PR TITLE
Fix Scalar Value Types Table for Markdown

### LINKED ISSUE #453: Scalar value types table malformed
Per specifications, markdown requires at least 3 dashes in the 2nd row of a table to be valid. As it seems to be taking the length of the programming language for the amount of dashes to add, it breaks with c# and go, and thus breaks the whole table.

### PR DESCRIPTION
**Pull request by ChristophGra**
As per the [markdown guidelines](https://www.markdownguide.org/extended-syntax/#tables) you need at least three dashes to have a properly formatted table. As the Go and C# example didn't have it, it caused the table to not render in Rider and Visual Studio. I suspect it will not render in others either.

Fixes #453

### CODE REVIEW

**Comment by ChristophGra** [comment]
@pseudomuto As per the Contributing.md, I am adding the the ping.

**Comment by pseudomuto** [comment]
Hey @ChristophGra, thanks for the PR! Can you please run `make examples` and add an entry to CHANGELOG.md under the unreleased heading?

**Comment by ChristophGra** [comment]
I must admit that I haven't worked with go before, so I'd appreciate it if you could point me to where I find the documentation on how to do that. I tried using go run but it gave me the error that it is not a main package. Furthermore, when I tried to run it via protoc, even though I ran go install on the package, I didn't get it to use the new version.

**Comment by ChristophGra** [comment]
Ok, @pseudomuto I got it to locally generate from the new template by passing it as a doc_opt and it has generated correct markdown, which rendered properly in VSCode, as well as Rider and Visual Studio.

**Comment by tmc** [comment]
@ChristophGra can you rebase this?

**Comment by ChristophGra** [comment]
@tmc like that? I hope I did the rebase right.

**Comment by pseudomuto** [comment]
@ChristophGra this looks 👌  Can you run `make examples` or `make docker_test` to ensure that the generated files are updated (I get a diff when I run it on this branch).

Once that's done we can get this merged....FINALLY 😬

**Pull request closed without merging**
