### PR TITLE
Render Message/Enums/Extensions/Services ranges only if present, to a…

### PR DESCRIPTION
**Pull request by horacimacias**
…void extra whitespace which ends up being seen as quote/code block

https://github.com/pseudomuto/protoc-gen-doc/issues/365

### CODE REVIEW

**Comment by pseudomuto** [comment]
Seems legit. Can you run `make examples` to update all the things?

**Comment by horacimacias** [comment]
I've updated makefile as at least for me it looked like some of the google proto files have been moved from https://github.com/googleapis/googleapis into https://github.com/protocolbuffers/protobuf.
Perhaps I'm missing something here or they are still in https://github.com/googleapis/googleapis in some tag/commit/branch.

After that, I re-generated resources and re-ran examples. The only difference in output for examples is the markdown, as expected, and now the several empty linebreaks are not there.
It's still not 100% free from linebreaks but at least it does not have the 3 it had before.

**Comment by pseudomuto** [comment]
LGTM 👍 Thanks for the PR!

**Comment by horacimacias** [comment]
perfect! thank *you*!

**Pull request merged**
