### PR TITLE
feat: source_relative

### PR DESCRIPTION
**Pull request by Rossiar**
adds support for generating the docs in the folder relative to the proto source path. If there are multiple directories containing proto files, adding the option `--doc_out=markdown,index.md,source_relative` will generate the file `index.md` under each of the proto directories with the documentation for the files in that directory. This PR satisfies https://github.com/pseudomuto/protoc-gen-doc/issues/449 and is a very lazy copy of https://github.com/pseudomuto/protoc-gen-doc/pull/399, which is simply out of date and I wasn't smart enough to fixup.

@pseudomuto it would be great to merge this as the `source_relative` opt is an [accepted option for protoc-gen-go](https://developers.google.com/protocol-buffers/docs/reference/go-generated#invocation) and will also allow this plugin to be used nicely with the lovely [`buf generate`](https://docs.buf.build/generate-usage/)

### CODE REVIEW

**Comment by pseudomuto** [comment]
Hey @Rossiar thanks for the PR! In general this looks good to me. I ran the tests and examples locally and things look good 👍 

Can you document the option in README.md and add an entry to the CHANGELOG.md file? Once that's done, I'll get this merged and cut a new release.

**Comment by Rossiar** [comment]
@pseudomuto all done

**Comment by pseudomuto** [comment]
v1.5.0 has been released (docker image will take a little longer). Thanks again for the PR!

**Comment by houseofmercy-github** [comment]
For the benefit of anyone else trying out this plugin with [buf](https://docs.buf.build/introduction) who may be unfamiliar with the relationship between the `buf.gen.yaml` settings and the corresponding `protoc-gen-doc` options, here is what worked for me:

```
version: v1
plugins:
  - name: doc
    out: ./gen/doc
    opt: html,index.html,source_relative
```

Note here since `name: doc` is specified the plugin is passed `--doc_opt=html,index.html,source_relative`.  

If you naively try to specify only the source_relative option like I first did e.g.
```
version: v1
plugins:
  - name: doc
    out: ./gen/doc
    opt: source_relative                   <--- don't do this it will fail
```

you will see `Invalid parameter: source_relative`because [ParseOptions](https://github.com/pseudomuto/protoc-gen-doc/blob/master/plugin.go#L138-L140) won't see a `,` 

The message isn't wrong but it's confusing and could be improved.  It would have saved me some time had it given the  [description in the comment a few lines earlier](https://github.com/pseudomuto/protoc-gen-doc/blob/master/plugin.go#L110-L111) e.g.

```
Invalid parameter: source_relative  
The parameter --doc_opt must be of the format
<TYPE|TEMPLATE_FILE>,<OUTPUT_FILE>[,default|source_relative]:<EXCLUDE_PATTERN>,<EXCLUDE_PATTERN>*.
```

**Comment by metux** [comment]
Links between documents still seem broken:
Just tried w/ html output. When subdir A references types from B, the links in A/index.html pointing to A/index.html instead of B/index.html.
The effect is the same as if one's doing two separate calls for each subdir.

**Pull request merged**
