### PR TITLE
Go port - fixes to markdown.tmpl ToC section

### PR DESCRIPTION
**Pull request by aschrijver**
Some changes to the table of contents for markdown, so that there are no superfluous line-feeds.

Note that: 
- there is still a line-feed before `.Name` of the file. This is probably inside of the variable
- the file .Description is empty, not rendered to output
- whitespace is stripped from code snippets

### CODE REVIEW

**Comment by aschrijver** [comment]
See for example: https://github.com/aschrijver/hypercore-protocol/blob/gh-pages/hypercore-protocol_custom-template.md

**Comment by pseudomuto** [comment]
This LGTM 👍 

Can you run `make examples` so that the example files get these changes? Then I'll merge it into #305

**Comment by aschrijver** [comment]
I don't have a working dev enviroment for running `make`

```
09:52 $ make examples
make: glide: Command not found
Makefile:21: recipe for target 'dependencies' failed
make: *** [dependencies] Error 127
```

**Comment by pseudomuto** [comment]
No worries then. I'll update them after. Thanks for the PR!

**Comment by aschrijver** [comment]
Thanks for merging :)

**Pull request merged**
