### PR TITLE
Support for Oneof in proto files

### PR DESCRIPTION
**Pull request by lpabon**
Also included a template to generate markdown from grpc proto spec

Signed-off-by: Luis Pabón <luis@portworx.com>

### CODE REVIEW

**Comment by jason-fox** [comment]
If this is a more up-to-date protokit compatible 1.1.0 compatible solution  to fix the issue #333 I personally would love to see `oneOf` added. 

I raised  PR #336 for this problem back in January, and I have been awaiting feedback ever since.  I have changed jobs in the last six months, and would no longer have time to commit to making further updates in Go to move my own PR forward, so assuming you are more active in the area I would like to see this effort move to a successful conclusion.

Does this also create a `oneOf` description from the comments as well as a flag? Do the templates need updating? Is there anything else you could amalgamate from my effort?

**Comment by Globegitter** [comment]
@pseudomuto anything blocking this from getting merged? Is it not compatible anymore with the latest version?

**Comment by nicolassleiman** [comment]
Any update?

**Comment by nicolassleiman** [comment]
Any update?

**Comment by guiguan** [comment]
Yes, please merge this one

**Comment by nielsvaneck** [comment]
@pseudomuto could this be merged & released?

**Comment by ping-localhost** [comment]
Can we please get this merged @pseudomuto. Anything I can do to help?

**Comment by ping-localhost** [comment]
Pinging @pseudomuto again. Anything I/we can do to help?

**Comment by ping-localhost** [comment]
Pinging @pseudomuto again. Anything I/we can do to help?

**Comment by pseudomuto** [comment]
At a glance this LGTM 👍 At this point it'll need a rebase

**Comment by ping-localhost** [comment]
> At a glance this LGTM 👍 At this point it'll need a rebase

Any chance you're able to do so @pseudomuto / @lpabon. Otherwise I'll take a crack at it :)

**Comment by fhalim** [comment]
Submitted https://github.com/pseudomuto/protoc-gen-doc/pull/436 to rebase this PR against current master.

**Comment by lpabon** [comment]
Hey guys! Just noticed this 4 years later now that I'm back on this again 😄 . Thank you so much for merging!

**Pull request closed without merging**
