### PR TITLE
Port to Go for 1.0 Release

### LINKED ISSUE #17: Add support for protobuf 3.0
Hello Elvis,
Many thanks for you project at first.
Are you going to support new version of protobuf 3.0? I suppose it's near release.

### LINKED ISSUE #288: Message enums are included in file_enums
Enums nested inside a message definition should be included as part of a new key "message_enums" instead of being included at the top file level "file_enums".

```protobuf
enum FileEnum {
    A = 1;
    B = 2;
}

message MyMessage {
    enum MessageEnum {
        C = 3;
        D = 4;
    }
}
```

```json
[
    {
        "file_description": "",
        "file_enums": [
            {
                "enum_description": "",
                "enum_full_name": "FileEnum",
                "enum_long_name": "FileEnum",
                "enum_name": "FileEnum",
                "enum_values": [
                    {
                        "value_description": "",
                        "value_name": "A",
                        "value_number": 1
                    },
                    {
                        "value_description": "",
                        "value_name": "B",
                        "value_number": 2
                    }
                ]
            },
            {
                "enum_description": "",
                "enum_full_name": "MyMessage.MessageEnum",
                "enum_long_name": "MyMessage.MessageEnum",
                "enum_name": "MessageEnum",
                "enum_values": [
                    {
                        "value_description": "",
                        "value_name": "C",
                        "value_number": 3
                    },
                    {
                        "value_description": "",
                        "value_name": "D",
                        "value_number": 4
                    }
                ]
            }
        ],
        "file_extensions": [
        ],
        "file_has_extensions": false,
        "file_has_services": false,
        "file_messages": [
            {
                "message_description": "",
                "message_extensions": [
                ],
                "message_fields": [
                ],
                "message_full_name": "MyMessage",
                "message_has_extensions": false,
                "message_long_name": "MyMessage",
                "message_name": "MyMessage"
            }
        ],
        "file_name": "test.proto",
        "file_package": "",
        "file_services": [
        ]
    }
]
```

### LINKED ISSUE #289: Include the "files" key name in generated json
When generating json, it would be better to include the "files" key followed by the value instead of just the value e.g.

```protobuf
enum FileEnum {
    A = 1;
    B = 2;
}

message MyMessage {
    enum MessageEnum {
        C = 3;
        D = 4;
    }
}
```
currently generates -

```json
[
    {
        "file_description": "",
        "file_enums": [
            {
                "enum_description": "",
                "enum_full_name": "FileEnum",
                "enum_long_name": "FileEnum",
                "enum_name": "FileEnum",
                "enum_values": [
                    {
                        "value_description": "",
                        "value_name": "A",
                        "value_number": 1
                    },
                    {
                        "value_description": "",
                        "value_name": "B",
                        "value_number": 2
                    }
                ]
            },
            {
                "enum_description": "",
                "enum_full_name": "MyMessage.MessageEnum",
                "enum_long_name": "MyMessage.MessageEnum",
                "enum_name": "MessageEnum",
                "enum_values": [
                    {
                        "value_description": "",
                        "value_name": "C",
                        "value_number": 3
                    },
                    {
                        "value_description": "",
                        "value_name": "D",
                        "value_number": 4
                    }
                ]
            }
        ],
        "file_extensions": [
        ],
        "file_has_extensions": false,
        "file_has_services": false,
        "file_messages": [
            {
                "message_description": "",
                "message_extensions": [
                ],
                "message_fields": [
                ],
                "message_full_name": "MyMessage",
                "message_has_extensions": false,
                "message_long_name": "MyMessage",
                "message_name": "MyMessage"
            }
        ],
        "file_name": "test.proto",
        "file_package": "",
        "file_services": [
        ]
    }
]
```
It would be better to generate -

```json
"files" : [ ... ]
```
This way the generated json can directly be piped to a external program like an external mustache engine.

### LINKED ISSUE #293: markdown.template lists are not correctly formatted
In the [markdown.template](https://github.com/pseudomuto/protoc-gen-doc/blob/master/templates/markdown.mustache) is a small bug that leads to wrong formatted lists.

This is also shown in the [markdown example](https://github.com/pseudomuto/protoc-gen-doc/blob/master/examples/doc/example.md)

The current output:

## Table of Contents
* [Booking.proto](#Booking.proto)
 * [Booking](#com.example.Booking)
 * [BookingStatus](#com.example.BookingStatus)
 * [BookingService](#com.example.BookingService)

Should be:
## Table of Contents
* [Booking.proto](#Booking.proto)
  * [Booking](#com.example.Booking)
  * [BookingStatus](#com.example.BookingStatus)
  * [BookingService](#com.example.BookingService)

The template should be adapted by simply adding an additional space.

Before change:

## Table of Contents
{{#files}}
* [{{file_name}}](#{{file_name}})
 {{#file_messages}}
 * [{{message_long_name}}](#{{message_full_name}})
 {{/file_messages}}
 {{#file_enums}}
 * [{{enum_long_name}}](#{{enum_full_name}})
 {{/file_enums}}
 {{#file_has_extensions}}
 * [File-level Extensions](#{{file_name}}-extensions)
 {{/file_has_extensions}}
 {{#file_services}}
 * [{{service_name}}](#{{service_full_name}})
 {{/file_services}}
{{/files}}

After change:

## Table of Contents
{{#files}}
* [{{file_name}}](#{{file_name}})
 {{#file_messages}}
  * [{{message_long_name}}](#{{message_full_name}})
 {{/file_messages}}
 {{#file_enums}}
 * [{{enum_long_name}}](#{{enum_full_name}})
 {{/file_enums}}
 {{#file_has_extensions}}
 * [File-level Extensions](#{{file_name}}-extensions)
 {{/file_has_extensions}}
 {{#file_services}}
 * [{{service_name}}](#{{service_full_name}})
 {{/file_services}}
{{/files}}

I tried to create a custom template based on the ```templates/markdown.mustache``` with the above shown changes but then the output is missing the whole ```{{#message_fields}}``` section. 

Thank you.

### LINKED ISSUE #298: Slashes end up in the html output when using triple-slash comments
Thanks for your nice project.

I noticed a bug when using triple-slash comments `///`. If you have this:

```javascript
/// Hypercore Info message.
message Info {

  /// If you have a comment line, like this, that occupies multiple lines here and is
  /// long enough to also break in html, then the html output contains a single forward
  /// slash that shouldn't be there.
  optional bool uploading = 1;
  optional bool downloading = 2;
}
```

When using the `/** ... */` style comments there are no issues, so I'm using only these now.

Versions:
- Ubuntu `16.04`
- libprotoc `2.6.1`
- protoc-gen-doc `0.9` (presumably, but `protoc-gen-doc --version` is not supported to confirm that)

### LINKED ISSUE #300: Field information not rendered with custom html.mustache templates
When copying the `html.mustache` locally and without modification run it like this:
```
protoc --doc_out=html2.mustache,index.html:build/html schemas/*.proto
```

Then all field tables are entirely missing in the output.
You can see the output in this gist: https://gist.github.com/aschrijver/0a2fb12347362ced80c6c5443fa8f40e

Switching back to internal template.. everything works.

Versions:
- Ubuntu 16.04
- libprotoc 2.6.1
- protoc-gen-doc 0.9 (presumably, but protoc-gen-doc --version is not supported to confirm that)

### LINKED ISSUE #303: Message headers in markdown broken due missing newline
In markdown output the Message headers are broken due to a missing newline:

Instead of:
```
### {{message_long_name}}
{{& message_description}}
```

It should be:
```
### {{message_long_name}}

{{& message_description}}
```

I will PR.

### LINKED ISSUE #311: Enum values seem to be enumerated, rather than taking the value defined
Hi,
Was wondering if anybody has come across this problem:

> option optimize_for=LITE_RUNTIME;
> 
> package com.test;
> 
> enum ErrorCode {
>     Value1              = 0;
>     Value2              = 2;
>     Value3              = 115;   
> }
> 

When executing this:

> protoc32 --docbook_out=.\doc --plugin=docbook_out=protoc-gen-doc.exe --proto_path=.\protobuf .\protobuf\Error.proto

The xml file generate has the wrong values for the enums :(

Any thoughts ?

### PR DESCRIPTION
**Pull request by pseudomuto**
Working on porting this project to go. More details to follow, these lists are works in progress as well.

**New Things**
* Support for proto3 (without losing anything from proto2) 🎉 
* Fairly comprehensive test coverage
* Bug fixes (see below)

**Breaking Changes (might address some of these)**:
* Invocation changed from parsing `--doc_out` to parsing `--doc_opt`.
* Templates are now golang templates, rather than mustache
* JSON output now includes top-level `files` object, and all names are `camelCased` to be more idiomatic
* No direct support for PDF, though fop would be easy to add back in

**Fixed Issues**:
* Fixes #17
* Fixes #288
* Fixes #289
* Fixes #293 
* Fixes #298 
* Fixes #300 
* Fixes #303 
* Fixes #311

### CODE REVIEW

**Comment by estan** [comment]
Very cool! I'm excited to see this happen, and humbled by being added as a potential reviewer.

However, I'm a complete Go rookie. Both Go and Rust has long been on my TODO of things to familiarize myself with, but I've been so preoccupied with work (where it's all C++/Python) that it's never happened.

I'm all for this port, but I think you better find someone else if you want a proper review. Or well, just say to hell with it and push, you're the maintainer now after all :)

**Comment by pseudomuto** [comment]
@estan thanks so much for all your reviews! Can I ask you one more favour?

I was wondering if you could try running it, just for my own sanity to make sure it's not one of those "works for me" situations :smile:

I've pushed 1.0.0-alpha, so the Docker image is available in DockerHub now.

https://github.com/pseudomuto/protoc-gen-doc/tree/3d7ea549ea28da4fd929fb6b20f24dd763355c11#using-the-docker-image-recommended

**Comment by pseudomuto** [comment]
@aschrijver I saw that you had opened a few issues that should be resolved with this PR. Any chance you'd be willing to give it a shot?

**Comment by aschrijver** [comment]
@pseudomuto Sure! Really nice work you've done here!
I'll update my issues, SO questions based on findings..

**Comment by aschrijver** [comment]
I need some help in using / building. Both the docker and go package are not yet there, only in `go_port` branch. Building locally `go build` or install doesn't do it as well.

```
plugin.go:5:2: cannot find package "github.com/golang/protobuf/proto" in any of:
	/usr/lib/go-1.6/src/github.com/golang/protobuf/proto (from $GOROOT)
	/home/arnold/go/src/github.com/golang/protobuf/proto (from $GOPATH)
plugin.go:6:2: cannot find package "github.com/golang/protobuf/protoc-gen-go/plugin" in any of:
	/usr/lib/go-1.6/src/github.com/golang/protobuf/protoc-gen-go/plugin (from $GOROOT)
	/home/arnold/go/src/github.com/golang/protobuf/protoc-gen-go/plugin (from $GOPATH)
plugin.go:7:2: cannot find package "github.com/pseudomuto/protoc-gen-doc/parser" in any of:
	/usr/lib/go-1.6/src/github.com/pseudomuto/protoc-gen-doc/parser (from $GOROOT)
	/home/arnold/go/src/github.com/pseudomuto/protoc-gen-doc/parser (from $GOPATH)
```

**Comment by aschrijver** [comment]
Or the docker image..

**Comment by pseudomuto** [comment]
Hmm...I did push an alpha build with the docker image. 

Are you able to get it using `docker pull pseudomuto/protoc-gen-doc`?

To test with a local build, take a look at CONTRIBUTING.md on this branch. Once you've got the dependencies you can run `make build` to build the binary.

Thanks so much for taking a look man, I really appreciate it!

**Comment by aschrijver** [comment]
Yep, I can pull the docker image now. I'll commence my tests later today! Thanks!

**Comment by aschrijver** [comment]
@pseudomuto there seems to be no way to specify a single `.proto` instead of a whole directory, am I right? I'm trying to do something like:

```
docker run --rm -v $(pwd)/build:/out -v $(pwd)/schemas:/protos pseudomuto/protoc-gen-doc 
     --doc_opt=md,hypercore-protocol.md schemas/HypercoreSpecV1_md.proto
```

**Comment by aschrijver** [comment]
Alright, I adjusted my TravisCI test project to the new version, and now have 2 branches to compare:

- https://github.com/aschrijver/hypercore-protocol/tree/feature/document-generator-new
- https://github.com/aschrijver/hypercore-protocol/tree/feature/document-generator

I didn't update the pro's/con's yet, and custom templates are same as standard still, but some first observations:

- it's not possible to specify individual `.proto`, so I used different directories instead
- there are still a number of things to fix in the generated output (compare old/new)

**Comment by pseudomuto** [comment]
Pushed a new build (and container) that addresses the issue of generating docs for individual files (can be multiple). You can get the latest by running `docker pull pseudomuto/protoc-gen-doc` again.

**Comment by aschrijver** [comment]
Great, I will test tomorrow. (I'm in CET, Netherlands)

**Comment by aschrijver** [comment]
This is a bit of a feature request, but putting here, since this is not yet live (I can create issues later).
As you can see in my example `.proto` there is a sequence to the messages which corresponds more or less to how the protocol works.

Having the message in the same sequence as defined in the `.proto` would be much more intuitive than having it alphabetically ordered.

So maybe the ordering could be set with a flag or something, or even an `@order` annotation.

**Comment by aschrijver** [comment]
@pseudomuto don't hesitate to give me a note when I should regenerate/retest my doc example project

**Comment by pseudomuto** [comment]
Hey @aschrijver. I've updated the examples with your PR applied. I put out a RC release (1.0.0-rc) which you can get with `docker pull pseudomuto/protoc-gen-doc`. Can you give it one more shot before launch?

As for your feature request, it seems like a pretty good idea. I'd be happy to work on that (or review a PR) for 1.1.0, but I'd really like to cut this release soon as this PR is already massive.

**Comment by aschrijver** [comment]
Hi @pseudomuto 

Thanks! I created a dedicated repository for the testing: https://github.com/aschrijver/protoc-gen-doc-example. There are a number of issues still in the template output.

HTML:
- takes line breaks literally from the comments, converts to `<p>` yielding too much line space
- code snippets have no indentation spaces
- protocol file description is not added to the output

Markdown:
- file name ToC title has line breaks in front of it
- code snippets have no indentation spaces
- protocol file description is not added to the output

**Comment by aschrijver** [comment]
I also updated my 2 stackoverflow answers that were about `protoc-gen-doc`:

- https://stackoverflow.com/a/45254099/8295283
- https://stackoverflow.com/a/45253665/8295283

**Comment by glasser** [comment]
This looks awesome. However, since you can't point `go get` at a branch, it's hard to install this directly until you merge it. Are you planning to merge it? Or maybe move it to a different GitHub repo?  (I could fork it to my own but would have to update all the internal package references...)

**Comment by glasser** [comment]
The nobr filter used in markdown descriptions seems pretty intense: it doesn't add spaces, so words at the end and beginning of lines get put directly together without a space.

**Comment by pseudomuto** [comment]
> This looks awesome. However, since you can't point go get at a branch, it's hard to install this directly until you merge it

Thanks man! I definitely am planning on merging this. I want to take a look at a few of the issues mentioned here first. 

In the meantime, the docker image is available, so you should be able to run it that way. https://github.com/pseudomuto/protoc-gen-doc/tree/go_port#using-the-docker-image-recommended

**Pull request merged**
