### PR TITLE
Update markdown.mustache, add missing crlf (#303)

### PR DESCRIPTION
**Pull request by aschrijver**
Added a couple of new lines to fix broken message headers in output.

### CODE REVIEW

**Comment by aschrijver** [comment]
Note, these are different line feeds than https://github.com/pseudomuto/protoc-gen-doc/pull/277/commits/207ead3000308aa493e5ac409a3d191959b0347e

**Comment by unlikely-leo** [comment]
The test failures look like flakes unrelated to the actual diff. I would like to see this merged too. Is there some way to trigger the tests again?

**Comment by aschrijver** [comment]
i am unfortunately not able to merge or deliver more PR's for a while
am building innercircles ...

the open-source movement for people!
who care for our world and want to be happier in it :)

**Comment by pseudomuto** [comment]
I believe this was addressed by #318 (since merged to master). If that's not the case, feel free to reopen.

**Pull request closed without merging**
