### PR TITLE
Recursively adding enums and messages from nested types.

### PR DESCRIPTION
**Pull request by aakoshh**
@pseudomuto I'd like to add a small change to the `template.go` file to support arbitrarily nested types:

**What is Changing?**
The `NewTemplate` method's way of collecting `Messages` and `Enums`. 

**How is it Changing?**
Instead of listing the messages in the file and the ones immediately nested below them, the template will recursively gather all nested messages and enums regardless of how deep they are.

**What Could Go Wrong?**
Nothing that I can see.

### CODE REVIEW

**Comment by JoelPM** [comment]
Any chance of getting this merged? I'd love to use protoc-gen-doc to generate docs, but I'm working with an object model that has deeply nested definitions.

**Comment by Lasconik** [comment]
We would also benefit from that!

**Comment by nejcgalof** [comment]
Any chance of getting this merged?

**Comment by fmcgough** [comment]
This PR is nearly 1 year old :birthday: what needs to happen for it to be merged?

**Comment by pseudomuto** [comment]
Apologies for the delay everyone

**Pull request merged**
