### PR TITLE
Bugfix for envoyproxy/validate extension

### PR DESCRIPTION
**Pull request by htdvisser**
This pull request contains a small bugfix (a single fallthrough statement) for the envoyproxy/validate extension (formerly lyft/validate) and moves it to envoyproxy_validate while keeping aliases in lyft_validate.

The bugfix is needed to make slice rules such as `in` and `not_in` work properly.

### CODE REVIEW

**Comment by htdvisser** [comment]
Hi @pseudomuto, this pull request has been open for almost a year now, so I rebased it on top of `master` to get it up-to-date again. Please let me know if this is something that might get merged, otherwise I'll just close the PR.

**Comment by pseudomuto** [comment]
Hey @htdvisser so sorry for the loooong delay. In the future, please `@` me on PRs so I get notified about them.

I'm good with this change 👍. Would you mind adding a line to CHANGELOG.md? Once that's done we'll get this merged and released.

**Comment by htdvisser** [comment]
Hi @pseudomuto, what exactly do you want me to add to the CHANGELOG? It already contains the following lines:

> * Renamed `lyft_validate` extension to `envoyproxy_validate`
> * Fixed `envoyproxy_validate` rules with slice values such as `in` and `not_in`

I didn't do anything else in this pull request, so I thought that would cover it

**Comment by pseudomuto** [comment]
Whoops! Somehow I blocked the md changes from my mind 😄 Thanks for the PR man!

**Comment by pseudomuto** [comment]
Released https://github.com/pseudomuto/protoc-gen-doc/releases/tag/v1.3.2 with these changes

**Pull request merged**
